spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/obertibussopaulina

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

final:
  keycloakOberti:
    serverUrl: http://localhost:8080/
    realm: obertibussopaulina
    clientId: api-user
    clientSecret: b1zDcURYKWo7SUPoS8lVw0Vl7MavbsQF